services:
  db:
    image: postgres:16
    container_name: medrec-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: medrec_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medrec_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: medrec-nginx
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db

volumes:
  pgdata:
